### ISSUE TITLE
Boundary value operators: final touchups

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqOperators.jl#148]
For the most part the boundary value operators are looking good after https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/135 . Some finishing details are:

- [x] Let Robin accept abstract vector
- [x] Simplified constructors don't need to allocate a vector
- [x] slicemul docstring space
- [ ] dim type parameter?

**Comment by xtalax** [comment]
Dim is a type parameter of MultiDimDirectionalBC - do you mean that it should be declared as such with a `where {dim}` in those constructors?

**Comment by xtalax** [comment]
@ChrisRackauckas solved in #149

**Comment by ChrisRackauckas** [comment]
Still the type parameter issue

**Comment by xtalax** [comment]
I was getting confusing errors trying to get it to work with a type parameter like that - since `MultiDimBC` is not a type, just a function name.

**Comment by ChrisRackauckas** [comment]
You need to fake it being a type.

**Comment by jagot** [comment]
> [x] Let Robin accept abstract vector

I wondered about this point; the constructor for the uniform case only accepts `Tuple`s whereas the non-uniform takes `AbstractVector`s. `GeneralBC` takes `AbstractVector`s for both cases.

**Comment by ChrisRackauckas** [comment]
Completed by https://github.com/SciML/DiffEqOperators.jl/pull/279
