### ISSUE TITLE
Missing Method + for GhostDerivativeOperator

### ISSUE THREAD

**Issue by avonramm92** [SciML/DiffEqOperators.jl#168]
From what I can tell so far there is currently no way to impose (Periodic, I haven't tested the other BCs) BC on problems which require adding multiple DerivativeOperators. One possibility to solve this might be to overload + for GhostDerivativeOperators?

**Comment by xtalax** [comment]
Thanks for bringing this up - just so we're looking at the same thing:
```
using DiffEqOperators

s = x, y, z = (-5:0.1:5, -5:0.1:5, -5:0.1:5)
dx = dy = dz = x[2] - x[1]

D2x = CenteredDifference{1}(2, 6, dx, length(x))
D2y = CenteredDifference{1}(2, 6, dy, length(y))
D2z = CenteredDifference{1}(2, 6, dz, length(z))

Q = compose(PeriodicBC{Float64}(length.(s))...)

∇² = D2x + D2y + D2z

gaussian(x::T, y::T, z::T) where T = exp(-(x^2 + y^2))
u0 = [gaussian(X,Y,Z) for Z in z, Y in y, X in x]

L = (∇²*Q)
```
`L` _should_ be a `GhostDerivativeOperator`, but it is actually a `DiffEqOperatorCombination`.

This is because `GhostDerivativeOperator` only accepts `AbstractDerivativeOperators` and not `AbstractDiffEqLinearOperators` - I'll make this change and see if I can get it working as intended

**Comment by avonramm92** [comment]
Hi, 
my example was quite a bit simpler, but I think it's the same issue: 
`using DiffEqOperators
using DifferentialEquations
using LinearAlgebra
using SparseArrays

Δx=0.1
N=40
u₀=1.0
Γ=1.0
Dx=u₀*CenteredDifference{1}(1,2,Δx,N)
Dxx=Γ*CenteredDifference{1}(2,2,Δx,N)
Q=PeriodicBC{Float64}()

A = Dx*Q + Dxx*Q`

**Comment by xtalax** [comment]
Just so that you know, for performance reasons it is reccomended to factor out `Q` like this: `A = (Dx+Dxx)*Q` - I'll add this to the docs for future reference.

It looks like the `GhostDerivativeOperator` is in need of a rewrite to get it to work with more complex operators.

**Comment by avonramm92** [comment]
Yes, i tried that also. 
it raises a different error though: LoadError: MethodError: no method matching SparseMatrixCSC(::PeriodicBC{Float64})Closest candidates are:
  SparseMatrixCSC(::PeriodicBC{T}, !Matched::Int64) where T at /home/avonramm/.julia/dev/DiffEqOperators/src/derivative_operators/concretization.jl:193
The other error message helped me more, so I started investigating there ;)

**Comment by avonramm92** [comment]
Not sure, if this is the same issue, but calling Array() on the GhostDerivativeOperator created by Dxx*Q from the example above raises LoadError: DimensionMismatch("second dimension of A, 42, does not match length of x, 40").
