### ISSUE TITLE
Performance benchmarking for laplacian example

### ISSUE THREAD

**Issue by xtalax** [SciML/DiffEqOperators.jl#178]
I have written a small benchmarking script based off the code [here](https://discourse.julialang.org/t/solving-the-diffusion-equation-in-julia/28811/10) -

```
using DiffEqOperators, BenchmarkTools

s = x, y= (-5:0.2:5, -5:0.2:5)
S = length.(s)

dx = dy = x[2] - x[1]

gaussian(x,y) = exp(-(x^2 + y^2))

laplacian(u) = (circshift(u, (1,0)) + circshift(u, (-1,0)) + circshift(u, (0, 1)) + circshift(u, (0,-1)) - 4*u)/(dx^2)

Dxx = CenteredDifference{1}(2, 2, dx, length(x))
Dyy = CenteredDifference{2}(2, 2, dy, length(y))

Q = compose(PeriodicBC(Float64, S)...)

L = (Dxx+Dyy)*Q

u = gaussian.(x, y')
```
then in the REPL:
```
julia> @benchmark L*u
BenchmarkTools.Trial: 
  memory estimate:  2.31 MiB
  allocs estimate:  74373
  --------------
  minimum time:     4.785 ms (0.00% GC)
  median time:      5.019 ms (0.00% GC)
  mean time:        5.313 ms (5.26% GC)
  maximum time:     8.471 ms (0.00% GC)
  --------------
  samples:          941
  evals/sample:     1

julia> @benchmark laplacian(u)
BenchmarkTools.Trial: 
  memory estimate:  163.81 KiB
  allocs estimate:  22
  --------------
  minimum time:     30.758 μs (0.00% GC)
  median time:      33.325 μs (0.00% GC)
  mean time:        43.181 μs (18.59% GC)
  maximum time:     1.358 ms (91.69% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

It seems that `DiffEqOperators` performs pretty poorly in this case - there are far too many allocations. Is there a way to see the full trace of function calls so we can work out which methods are at fault?

**Comment by ChrisRackauckas** [comment]
Use the profiler and ProfileView.jl to get a flamegraph. Is this case using NNLib?

**Comment by xtalax** [comment]
It should be, that's why I want to inspect the function calls to see what's up.

**Comment by xtalax** [comment]
It does appear to be calling `conv` as expected - it's just taking ages because it's not specialized for `BoundaryPaddedArray` so it's calling getindex on this type directly which is really slow because of the branching.

**Comment by ChrisRackauckas** [comment]
It should only `conv` the interior.

**Comment by ChrisRackauckas** [comment]
Should get a new version.
