### ISSUE TITLE
Coef_func broken

### ISSUE THREAD

**Issue by FuZhiyu** [SciML/DiffEqOperators.jl#198]
I identified several issues with the coef_func:

Basic setup:

```
using DiffEqOperators
nknots = 10
h = 1.0/nknots
x = 1.0:10.0
bc = DirichletBC(0.0, 11.0)

Δ = CenteredDifference(1, 2, h, nknots)
Δ * (bc * x)
```

This returns a vector of 10, as expected.

If I pass any callable to the coef_func argument of CenteredDifference, the operator totally broke down:

```
Δ = CenteredDifference(1, 2, h, nknots, x-> h)
Δ * (bc * x)
```
This returns a vector of 0.

Of course, the coefficient for centereddifference function doesn't really matter, but other issues arise for UpwindDifference, mainly related with the treatment of boundaries:

```
Δ = UpwindDifference(1, 1, h, nknots, x-> h * x)
Δ * (bc * x)
```
This returns `[1,2,1,2,3,4,5,6,-9,-10]`.  It seems that the coefficients are mismatched: They are only applied from the third entry. Also, there seem to be a problem with the right boundary.

If we concretize Δ, the mismatching is fixed:

```
Array(Δ) * (bc * x)
```
which returns `[1,2,3,4,5,6,7,8,-9,-10]`, though there are still problems with the right boundary.

**Comment by FuZhiyu** [comment]
I might totally misunderstood, but I'm a little confused by the current treatment of the right boundary. We have the negative derivative at the right boundary because the `high_boundary_coefs ` are obtained by reverse the `low_boundary_coefs`, as: 

```
high_boundary_coefs     = convert(SVector{boundary_point_count},reverse(SVector{boundary_stencil_length, T}[reverse(low_boundary_coefs[i]) for i in 1:boundary_point_count]))
```

 I understand the first reverse, but why should we reverse the coefficients? Won't it generate the opposite direction of derivatives? 

This happens for both CenterDifference and UpwindDifference. It would be really appreciated if anyone could clarify it to me.

**Comment by ChrisRackauckas** [comment]
I am not sure anything with the upwind operators works, so I wouldn't be surprised if the coefficients are off there. For CenteredDifference it should be good though. 

However, your function doesn't make sense. As the doc states:

>An operational argument for a coefficient function f(du,u,p,t) which sets the coefficients of the operator.

I am actually surprised your example doesn't just error.

**Comment by FuZhiyu** [comment]
> However, your function doesn't make sense. As the doc states:
> 
> > An operational argument for a coefficient function f(du,u,p,t) which sets the coefficients of the operator.
> 
> I am actually surprised your example doesn't just error.

The documentation actually is very confusing to me, because in the current implementation, coef_func is a function that maps from the index of the x to the coefficient, as below:

```
    for i in 1:len
        coefficients[i] = coeff_func(i)
    end
```
