### ISSUE TITLE
Higher-dimension CenteredDifference{N}

### ISSUE THREAD

**Issue by grahamas** [SciML/DiffEqOperators.jl#238]
```
u = zeros(10, 20)
dim = 2
boundary_operator = Dirichlet0BC(eltype(u))
derivative_operator = CenteredDifference{dim}(1, 2, 0.5, size(u, dim))
du =  derivative_operator * boundary_operator * u
```
Gives
```
ERROR: AssertionError: size(M, 1) == A.L.len
Stacktrace:
 [1] * at /home/graham/.julia/packages/DiffEqOperators/QiB3a/src/derivative_operators/ghost_derivative_operator.jl:34 [inlined]
 [2] *(::DerivativeOperator{Float64,2,false,Float64,StaticArrays.SArray{Tuple{3},Float64,1,3},StaticArrays.SArray{Tuple{0},StaticArrays.SArray{Tuple{3},Float64,1,3},1,0},Nothing,Nothing}, ::RobinBC{Float64,Array{Float64,1}}, ::Array{Float64,2}) at ./operators.jl:529
 [3] top-level scope at REPL[18]:1
```

However, if you set `dim=1` it works fine. Alternatively, if you keep `dim=2` but set the fourth argument (`len`) of `CenteredDifference{2}` to be `size(u, 1)`, then you don't get an error. Am I misunderstanding either the `len` argument, or the parameter?

If you set one of the rows to be nonzero (e.g. `u[5,:] .= 3.0`), the latter `CenteredDifference{2}` with `len=size(u,1)` produces the same output as when `dim = 1`, suggesting that the `{2}` is not changing the direction of the differencing the way I would expect.

**Comment by ChrisRackauckas** [comment]
It's because the boundary operator is acting by default in the first dimension here. You need to set it to the second dimension, which is something we need to update our interface on.

**Comment by grahamas** [comment]
Based on your comment I went looking around to see how hard it would be to implement. It looks like at least the interface is written in `multi_dim_bc_operators.jl`.  I ran into a bug already, but if it's just simple bugs I'll see if I can get it to a PR.  Assuming that's the interface you want, of course.

**Comment by ChrisRackauckas** [comment]
There is a big push here to finish it: https://github.com/SciML/DiffEqOperators.jl/pull/170 . The contributor had an unfortunate accident though, and we haven't been able to finish up this work.

**Comment by xtalax** [comment]
Hi, unfortunate contributor here. 

As it happens I should be getting set up with voice coding soon ([Talon](https://talonvoice.com/) for those interested) for better throughput, and you can bet that finishing this up will be my first project once that's sorted. Stay tuned!

**Comment by ChrisRackauckas** [comment]
Finished in https://github.com/SciML/DiffEqOperators.jl/pull/279 ! Thank you everyone who was involved!
