### ISSUE TITLE
Reference to hidden pdf

### ISSUE THREAD

**Issue by mindlike** [SciML/DiffEqOperators.jl#239]
docstrings.jl references a `ghost_node.pdf`, which I've found quite helpful. The URL gives the impression that this document is in the repo, but I don't see it. The link somehow still works.

https://github.com/SciML/DiffEqOperators.jl/blob/3cce15f027adb2e5adc32ef7427d6c944e3922e8/src/docstrings.jl#L154

https://github.com/JuliaDiffEq/DiffEqOperators.jl/files/3267835/ghost_node.pdf

Seems like the best fix would be to host the pdf elsewhere and update the link.

I'm also curious if there are other helpful hidden PDFs that got lost...

**Comment by ChrisRackauckas** [comment]
Possibly. It's kind of a dev note though. It's just a link to a file posted in a Github issue, so it will stay forever.

**Comment by mindlike** [comment]
Ah, makes sense. I've incorporated it into the notes I'm compiling.
