### ISSUE TITLE
Usage of boundary conditions with higher dimensional operators

### ISSUE THREAD

**Issue by LouieSlocombe** [SciML/DiffEqOperators.jl#245]
Hi,
I apologise if this is the wrong channel to ask this type of question. But, from reading the documentation it is not clear to me how one would go about combing boundary conditions with higher dimensional operators. 
As an example, say I wanted to impose Dirichlet boundary conditions on the following problem,
$u_{t} = u_{xx} + u_{yy}
I would start with something like this...

```julia
using DiffEqOperators

N = 64
x = range(-5, stop=5, length=N)
y = transpose(x)
dx = x[2]-x[1]

u = exp.(-x.^2 .-x'.^2)

Dxx = CenteredDifference{1}(2,2,dx,N)
Dyy = CenteredDifference{2}(2,2,dx,N)
L = Dxx + Dyy

Qx, Qy= MultiDimBC(Dirichlet0BC(eltype(u)),size(u))
Q = compose(Qx, Qy)

L * Q * u # DimensionMismatch
```

Could somebody suggest a correct way to go about it? Many thanks in advance!

**Comment by ChrisRackauckas** [comment]
That's how it's supposed to go, but I think we need to do a bit more work for it to all work out. https://github.com/SciML/DiffEqOperators.jl/pull/170 is the key.

**Comment by LouieSlocombe** [comment]
Thanks for your response, Chris. Keep up the good work. I will look over the thread, I would offer to help but unfortunately I late on joining the Julia gang so I don't think I will be of much use at this moment in time.
