### ISSUE TITLE
how does coeff_func work?

### ISSUE THREAD

**Issue by JianghuiDu** [SciML/DiffEqOperators.jl#266]
It's not clear to me what it does. So it is a function of the form `f(du,u,p,t)` to compute `coefficients`, is that it? How are the `coefficients` applied to the discretization? The `stencil_coefs` are the coefficients of the finite difference methods, for example, `[-0.5/h,0,0.5/h]` for centered difference of 1st order derivative. Is that correct? Not matter what I supply the final derivatives are always zero.

**Comment by ChrisRackauckas** [comment]
That stencil is correct. Crazy guess: are you doing `du = L*u` instead of mutating, i.e. `mul!(du,L,u)`?

**Comment by JianghuiDu** [comment]
To begin with I don't understand what `coeff_func` does and what the `coefficients` field in the operator mean, and how are they related to `stencil_coefs`. I need a finite difference scheme that is a weighted mean of centered and upwind differences. I wonder if there is a way to apply weights.

**Comment by ChrisRackauckas** [comment]
They are the coefficients multiplied to the array. That are needed in things like upwinding to know the winding direction. The applied stencil is the coefficient multiplied to the stencil.

**Comment by ChrisRackauckas** [comment]
It's just removed.
