### ISSUE TITLE
Bounds issues

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqOperators.jl#270]
From @YingboMa 's PR, it looks like DiffEqOperators is getting hit with some bounding issues from DataStructures stuff as well (@devmotion). It would be good to pin that down since it's affecting the downstream tests.

https://travis-ci.org/github/SciML/OrdinaryDiffEq.jl/jobs/723537160#L917-L1167

**Comment by devmotion** [comment]
Why should that be related to DataStructures? DiffEqOperators does not depend on DataStructures, and checking out DiffEqOperators and adding DataStructures@0.18 to its Project.toml works fine.

**Comment by ChrisRackauckas** [comment]
It showed up at the same time and then suddenly something is bounding it back, but I guess it's not... I can't pinpoint what it is.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/DiffEqOperators.jl/pull/271
