### ISSUE TITLE
2D heat equation

### ISSUE THREAD

**Issue by mbarbry** [SciML/DiffEqOperators.jl#274]
Dear Julia developers,

I'm trying to solve the heat equation in 2D. Before explaining my problem, I would like to stress that I'm a new Julia user, and my questions may be basic.

Let write the heat equation (in 2D) as

    du/dt = laplacian(u) + f(x, y, t)

My question is regarding the source term `f`. I'm not sure how to handle it.
Using the 1D example, I managed to get a the following lines running

    Δ = CenteredDifference{2}(ord_deriv, ord_approx, dx, Nx);
    bc = Dirichlet0BC(Float64);

    t0 = 0.0;
    t1 = tmax;

    u0 = fill(0.0, (Nx, Ny));
    step(u,p,t) = alpha*Δ*bc*u + moving_spot(u, X, Y, xoftime, yoftime, time_range, sigma, t);
    prob = ODEProblem(step, u0, (t0, t1), dtmax=0.01);
    alg = KenCarp4();
    sol = solve(prob, alg);

As you can see, my source function is call `moving_spot`. It takes `u` and `t` as arguments as well as others parameters. I'm wondering if this is the correct way to set up the problem, particularly, how do I pass the other parameters required by the function? How `ODEProblem` and `solve` know where to pass the time parameter `t`?

For information,

* `X` and `Y` (float 2D array) are the mesh grid of the system 
* `xoftime` and `yoftime` (float 1D array) are the position of the spot as function of time
* `time_range` (float 1D array)

`moving spot` return a 2D array of the dimension of the problem (gaussian spot at some position in time). As I said, the code is running, but the results are not as I expected. Therefore I wonder if the source term is properly used.

Thanks in advance for your help.

Best regards,
Marc Barbry

**Comment by ChrisRackauckas** [comment]
>As you can see, my source function is call moving_spot. It takes u and t as arguments as well as others parameters. I'm wondering if this is the correct way to set up the problem, particularly, how do I pass the other parameters required by the function?

This looks fine.

>How ODEProblem and solve know where to pass the time parameter t?

It passes the `t` for the current value.

Your issue is that this is not the Heat Equation in 2D. You have a 1-dimensional operator in the y direction. The Laplacian needs two derivative operators:

```julia
Dx = CenteredDifference{1}(ord_deriv, ord_approx, dx, Nx);
Dy = CenteredDifference{2}(ord_deriv, ord_approx, dx, Nx);
bc = Dirichlet0BC(Float64);
```

and then:

```julia
step(u,p,t) = alpha*(Dx*bc*u + Dy*bc*u) + moving_spot(u, X, Y, xoftime, yoftime, time_range, sigma, t);
```

Should be good. Let me know if you need more help.

**Comment by kkakosim** [comment]
I work on something similar, but I couldn't figure out from the tests & examples how to apply the rest of the BC's types (except for the D0BC). Have you used other BCs?

**Comment by ChrisRackauckas** [comment]
We're writing a bunch more documentation over the summer. You should consider this library as still a bit WIP until that's all completed (there are some notes in the docs saying that too).

**Comment by kkakosim** [comment]
totally clear and looking forward to that, your efforts are much appreciated, in the mean time, some of the /tests help indirectly

**Comment by chris-revell** [comment]
> > As you can see, my source function is call moving_spot. It takes u and t as arguments as well as others parameters. I'm wondering if this is the correct way to set up the problem, particularly, how do I pass the other parameters required by the function?
> 
> This looks fine.
> 
> > How ODEProblem and solve know where to pass the time parameter t?
> 
> It passes the `t` for the current value.
> 
> Your issue is that this is not the Heat Equation in 2D. You have a 1-dimensional operator in the y direction. The Laplacian needs two derivative operators:
> 
> ```julia
> Dx = CenteredDifference{1}(ord_deriv, ord_approx, dx, Nx);
> Dy = CenteredDifference{2}(ord_deriv, ord_approx, dx, Nx);
> bc = Dirichlet0BC(Float64);
> ```
> 
> and then:
> 
> ```julia
> step(u,p,t) = alpha*(Dx*bc*u + Dy*bc*u) + moving_spot(u, X, Y, xoftime, yoftime, time_range, sigma, t);
> ```
> 
> Should be good. Let me know if you need more help.

Sorry to restart this thread, but I'm currently trying to reproduce this 2D heat equation solution and am getting an error that I don't understand.

```
using DifferentialEquations
using DiffEqOperators
using Plots

tMax       = 0.1     # Run time
Nx         = 20      # Grid dimensions
dx         = 1/(Nx-1)# Grid spacing
alpha      = 1       # Diffusivity
ord_deriv  = 2       # Derivative order 
ord_approx = 3       # Derivative approximation order 
tSpan      = (0.0, tMax)

# Initial conditions zero apart from a small square in the middle
u0 = zeros(Float64,Nx,Nx)
u0[9:11,9:11] .= 1.0

# 1st and 2nd spatial dimension derivative operators 
Dx = CenteredDifference{1}(ord_deriv,ord_approx,dx,Nx)
Dy = CenteredDifference{2}(ord_deriv,ord_approx,dx,Nx)
bc = Dirichlet0BC(Float64)

# Time derivative function 
step(u,p,t) = alpha*(Dx*bc*u + Dy*bc*u)

prob = ODEProblem(step, u0, tSpan)
alg = KenCarp4()
sol = solve(prob, alg)

@gif for i=1:(size(sol.t)[1])
   heatmap(sol.u[i],clims=(0,1),aspect_ratio=:equal)
end every 5
```

This produces an error at line 27 (`sol=solve(prob,alg)`) as follows:
```
ERROR: LoadError: AssertionError: size(x_temp, N) + 2 == size(M, N)
Stacktrace:
  [1] mul!(x_temp::Matrix{Float64}, A::DerivativeOperator{Float64, 2, false, Float64, StaticArrays.SVector{5, Float64}, StaticArrays.SVector{1, StaticArrays.SVector{5, Float64}}, Nothing, Nothing}, M::DiffEqOperators.BoundaryPaddedArray{Float64, 1, 2, 1, Matrix{Float64}, Vector{Float64}})
    @ DiffEqOperators ~/.julia/packages/DiffEqOperators/5mEx8/src/derivative_operators/derivative_operator_functions.jl:76
```

This is running with Julia 1.6 and - as far as I'm aware - the latest package versions. Can anyone suggest why this isn't working? Many thanks.

**Comment by ChrisRackauckas** [comment]
it's getting completely rewritten and was labelled as experimental before. I hope to get a new version up ASAP.

**Comment by chris-revell** [comment]
I see, thank your for explaining. Apologies for querying, but I couldn’t understand why I wasn’t able to reproduce the behaviour from this thread!

**Comment by ChrisRackauckas** [comment]
Yup no worries, these issues should be gone soon enough. But in the documentation it says it's experimental and use at your own risk, because it's still quite under development.
