### ISSUE TITLE
Use RuntimeGeneratedFunctions for the evals in the MOLFiniteDifference

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqOperators.jl#283]
https://github.com/SciML/DiffEqOperators.jl/pull/250#discussion_r498583766

We should make use of https://github.com/SciML/RuntimeGeneratedFunctions.jl instead of `@eval` . The reason is because if you put `eval` into a function and then call that function within the same generating function, you'll get the classic world-age error. This works around the world-age error that will inevitably show up when users begin to use this functionality.

**Comment by emmanuellujan** [comment]
Thanks. I have two questions.

The current version of the code is working by using ``Base.invokelatest()`` to avoid the world-age error. But now I am not sure, how would the world-age error arise in the current code?

On the other hand, I think ``Base.invokelatest()`` can prevent some optimizations, and on the contrary, ``RuntimeGeneratedFunctions`` preserves these optimizations. Is this correct?

**Comment by ChrisRackauckas** [comment]
Oh yes, invokelatest works but is extremely slow, and yes this will optimize through.
