### ISSUE TITLE
Can't use `mul!` with GhostDerivativeOperator

### ISSUE THREAD

**Issue by stillyslalom** [SciML/DiffEqOperators.jl#298]
On Julia nightly, DiffEqOperators.jl master:
```
using LinearAlgebra, DiffEqOperators

xx = LinRange(0, 1, 256)
u = rand(256)
u′ = zeros(256)
mul!(u′, CenteredDifference(1, 2, step(xx), length(xx))*PeriodicBC(Float64), u)
```
```
ERROR: MethodError: Cannot `convert` an object of type
  GhostDerivativeOperator{Float64, DerivativeOperator{Float64, 1, false, Float64, StaticArrays.SVector{3, Float64}, StaticArrays.SVector{0, StaticArrays.SVector{3, Float64}}, Nothing, Nothing}, PeriodicBC{Float64}} to an object of type
  AbstractMatrix{T} where T
Closest candidates are:
  convert(::Type{AbstractMatrix{T} where T}, ::DiffEqOperators.DiffEqScaledOperator) at /home/aames/.julia/packages/DiffEqOperators/yjO9K/src/composite_operators.jl:24
  convert(::Type{AbstractMatrix{T} where T}, ::DerivativeOperator) at /home/aames/.julia/packages/DiffEqOperators/yjO9K/src/derivative_operators/concretization.jl:63
  convert(::Type{T}, ::Factorization) where T<:AbstractArray at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/factorization.jl:58
  ...
Stacktrace:
 [1] mul!(Y::Vector{Float64}, L::GhostDerivativeOperator{Float64, DerivativeOperator{Float64, 1, false, Float64, StaticArrays.SVector{3, Float64}, StaticArrays.SVector{0, StaticArrays.SVector{3, Float64}}, Nothing, Nothing}, PeriodicBC{Float64}}, B::Vector{Float64})
   @ DiffEqBase ~/.julia/packages/DiffEqBase/b38LC/src/operators/common_defaults.jl:17
 [2] top-level scope
   @ REPL[23]:1
```
Probably due to missing concretization methods for `GhostDerivativeOperator`s.

**Comment by grahamas** [comment]
`mul!` wasn't defined for GhostDerivativeOperators because they can't be done in place (as far as I recall)

**Comment by stillyslalom** [comment]
Seems like the scratch space could be rolled into the GhostDerivativeOperator struct by default, especially since it's also needed for `L*u`.

...unless you're working with several derivative operators that could potentially share scratch space, but even then, the scratch variable from one operator could just be provided as an argument to the constructor for another.

**Comment by ChrisRackauckas** [comment]
It could be in-place. The actual convolution operation under the hood is in-place. This is just an omission.

**Comment by grahamas** [comment]
Oh! The boundary padded array won't actually allocate! (other than the ref and the two floats) Sorry -- I looked into doing this before, and got confused.  I can take a crack at it now, if you're not already doing it.  Should be straightforward.

**Comment by ChrisRackauckas** [comment]
I'm not taking a look at it: I have to make sure our whole CI infrastructure gets updated to Github Actions 😱

**Comment by grahamas** [comment]
Yikes, good luck 😬

**Comment by stillyslalom** [comment]
I filed the issue, went to bed, woke up, and found it’d been fixed. @grahamas I question your sleep schedule, but I can’t fault the results!
