### ISSUE TITLE
Add Neumann and Robin boundary conditions to MOLFiniteDifference

### ISSUE THREAD

**Issue by tinosulzer** [SciML/DiffEqOperators.jl#300]
Currently, the MTK format only accepts boundary conditions of the form
```julia
bcs = [u(0,x) ~ -x*(x-1)*sin(x),
        u(t,0) ~ 0.0,
        u(t,1) ~ 0.0]
```
It would be good to add Neumann and Robin conditions, e.g.:
```julia
bcs = [u(0,x) ~ -x*(x-1)*sin(x),
        Dx(u(t,0)) ~ 0.0,
        u(t,1) + 2Dx(u(t,1)) ~ 0.0]
```
Comments on the API are welcome @ChrisRackauckas @emmanuellujan 

Also, it might be better to tackle #283 first, since this targets the same code

EDIT: I see NeuralPDE.jl does `Dx(u(t,0))` instead of `Dx(u)(t,0)`, so perhaps better to stick with that for consistency

**Comment by emmanuellujan** [comment]
> EDIT: I see NeuralPDE.jl does Dx(u(t,0)) instead of Dx(u)(t,0), so perhaps better to stick with that for consistency

> Also, it might be better to tackle #283 first

I agree

**Comment by tinosulzer** [comment]
What kind of error should be thrown if invalid boundary conditions are provided?
Should we raise a specific `BoundaryConditionError`? And if so, where (and how) should new exceptions be defined?

**Comment by ChrisRackauckas** [comment]
MTK doesn't check because NeuralPDE.jl can do a lot more generalized BCs. But we can throw a specific error if someone implements it. We haven't done well with specialized errors.

**Comment by tinosulzer** [comment]
Ok so I will start an `exceptions.jl` file under `src` with
```julia
type BoundaryConditionError <: Exception
    msg::String
end

Base.showerror(io::IO, e::BoundaryConditionError) = print(io, e.msg)
```

**Comment by tinosulzer** [comment]
What should `dx` be in `RobinBC`? Just `x[2:end] - x[1:end-1]`?
