### ISSUE TITLE
Automatically return extrapolated solution

### ISSUE THREAD

**Issue by tinosulzer** [SciML/DiffEqOperators.jl#305]
Right now, a solution needs to be multiplied by `prob.extrapolation` to obtain the solution including boundary conditions.
Should this be done automatically instead?
`solve` receives all the necessary information to do so (contained in the `PDEProblem`)

**Comment by ChrisRackauckas** [comment]
Yes, there's a similar issue in NeuralPDE. Different discretizations all end up doing standard numerical problems, but afterwards they  want to take the solution have some common way to analyze the result. This'll take some thinking to unify how to do this.

**Comment by tinosulzer** [comment]
I don't have the big picture for a unified solution with NeuralPDE, but for the MOL cases at the very least the solution should be returned at the points in `prob.space`. Since `prob` stores the discretization this should be possible even allowing for different MOL discretizations (FiniteDifference, FiniteElement, FiniteVolume, etc)

**Comment by ChrisRackauckas** [comment]
Superseded by https://github.com/SciML/DiffEqOperators.jl/issues/357
