### ISSUE TITLE
Few errors when running examples

### ISSUE THREAD

**Issue by Mrc010** [SciML/DiffEqOperators.jl#323]
When I was trying to run the [Examples ](http://diffeqoperators.sciml.ai/stable/examples/) I kept on getting the error `discretize not defined` until I found that it's a function of the OrdinaryDiffEq package which is called after the function is called.

Also, for the part 

```
for i in 1:length(t)
    plot!(x,Array(prob.extrapolation[1](t[i])*sol.u[i]),label="Numerical, t=$(t[i])")
    scatter!(x, u_exact(x, t[i]),label="Exact, t=$(t[i])")
end
```

I get a `MethodError: no method matching SparseMatrixCSC(::RobinBC{Float64,Array{Float64,1}})`.

I'm using Julia Version 1.4.2 (2020-05-23)

**Comment by ChrisRackauckas** [comment]
It probably requires Julia v1.5. But we should put a WIP note on that example: that's part of the unreleased interface for auto PDE solving. Exciting, but not complete.

**Comment by ChrisRackauckas** [comment]
I made the docs much more clear about what's a work in progress. This piece is definitely not ready for the average user. I also cleaned up the docs a bunch and added the required `using OrdinaryDiffEq` there, but I think this was missing a test and regressed.

**Comment by Mrc010** [comment]
> 
> 
> It probably requires Julia v1.5. But we should put a WIP note on that example: that's part of the unreleased interface for auto PDE solving. Exciting, but not complete.

Getting the same error with Julia Version 1.5.3 (2020-11-09).

**Comment by ChrisRackauckas** [comment]
Fixed.
