### ISSUE TITLE
Double check Robin BC handling heat equation tutorial in MOLFiniteDifference

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqOperators.jl#351]
Double check the Robin tutorial's solution. See https://github.com/SciML/DiffEqOperators.jl/pull/349#issuecomment-808837455 .

@tinosulzer ?

**Comment by tinosulzer** [comment]
Weird. I'm sure the tutorial is correct (d/dx(sin(x)) = cos(x)). Here is the solution of the Robin example when it was added, commit `ce1a3f1a15add43b7ddf8b68773ad21770c864fe`
![plot](https://user-images.githubusercontent.com/20817509/112754934-711ffa00-8fac-11eb-8ad8-5d55e92e4d31.png)

We could always add a helper function for testing that given an exact solution and the required BC format spits out the IC and BCs that will give the exact solution

**Comment by ChrisRackauckas** [comment]
That's not the part I'm worried about. I'm worried that the initial Robin conditions may have flipped the sign on the Dx term. Because of how they were specialized they were not hitting the same code as the Neumann, which would allow such a sign change to occur and would explain some of these results. In the new form, it's done completely by substitution, so such a sign change could not occur since the same exact substitution is done in the Neumann and Robin cases, and the equations are exactly eliminated by equality.

**Comment by tinosulzer** [comment]
The Neumann is broken in the new form too
```julia
using OrdinaryDiffEq, ModelingToolkit, DiffEqOperators
# Method of Manufactured Solutions: exact solution
u_exact = (x,t) -> exp.(-t) * cos.(x)

# Parameters, variables, and derivatives
@parameters t x
@variables u(..)
Dt = Differential(t)
Dx = Differential(x)
Dxx = Differential(x)^2

# 1D PDE and boundary conditions
eq  = Dt(u(t,x)) ~ Dxx(u(t,x))
bcs = [u(0,x) ~ cos(x),
        Dx(u(t,-1)) ~ -exp(-t) * sin(-1),
        Dx(u(t,1)) ~ -exp(-t) * sin(1)]

# Space and time domains
domains = [t ∈ IntervalDomain(0.0,1.0),
        x ∈ IntervalDomain(-1.0,1.0)]

# PDE system
pdesys = PDESystem(eq,bcs,domains,[t,x],[u(t,x)])

# Method of lines discretization
# Need a small dx here for accuracy
dx = 0.01
order = 2
discretization = MOLFiniteDifference([x=>dx],t)

# Convert the PDE problem into an ODE problem
prob = discretize(pdesys,discretization)

# Solve ODE problem
using OrdinaryDiffEq
sol = solve(prob,Tsit5(),saveat=0.2)

# Plot results and compare with exact solution
x = (-1:dx:1)[2:end-1]
t = sol.t

using Plots
plt = plot()

for i in 1:length(t)
    plot!(x,sol.u[i],label="Numerical, t=$(t[i])",lw=12)
    scatter!(x, u_exact(x, t[i]),label="Exact, t=$(t[i])")
end
display(plt)
savefig("plot.png")
```
![plot](https://user-images.githubusercontent.com/20817509/112763272-cae6eb00-8fd1-11eb-8d18-19920b8de93a.png)

it just happened to work in the case where the left bc was homogeneous neumann

**Comment by tinosulzer** [comment]
Both Robin and Neumann work if defining the Dx part of the left BC with the wrong sign, so I think there's a sign error in the new form related to that

**Comment by tinosulzer** [comment]
Found the problem, will submit a PR
