### ISSUE TITLE
Allow order choice in central difference handling of MOLFiniteDifference

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqOperators.jl#352]
After https://github.com/SciML/DiffEqOperators.jl/pull/349 it's hardcoded. One needs to generalize the lines:

```julia
        central_neighbor_idxs(i,j) = [i+CartesianIndex([ifelse(l==j,-1,0) for l in 1:length(nottime)]...),i,i+CartesianIndex([ifelse(l==j,1,0) for l in 1:length(nottime)]...)]
        central_weights(i,j) = DiffEqOperators.calculate_weights(2, 0.0, [space[j][i[j]-1],space[j][i[j]],space[j][i[j]+1]])
        central_deriv_rules = [(Differential(nottime[j])^2)(pdesys.depvars[k]) => dot(central_weights(i,j),depvars[k][central_neighbor_idxs(i,j)]) for j in 1:length(nottime), k in 1:length(pdesys.depvars)]
```

Note from the Fornberg that the order is determined by the number of stencil points:

https://github.com/SciML/DiffEqOperators.jl/blob/v4.22.0/src/derivative_operators/fornberg.jl#L2-L16

In the `CenteredDifference` operator you can see how it's done:

https://github.com/SciML/DiffEqOperators.jl/blob/v4.22.0/src/derivative_operators/derivative_operator.jl#L128

**Comment by tinosulzer** [comment]
What does `x0` do in `calculate_weights`? I see you just set it to 0 everywhere

**Comment by ChrisRackauckas** [comment]
It's mostly for type dispatch at this point. That needs to get refactored a bit, since it should probably be pulling that from the stencil types.

**Comment by tinosulzer** [comment]
This can be closed
