### ISSUE TITLE
Broken Heat Equation Robin tests

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqOperators.jl#36]
https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/test/heat_eqn.jl#L59

**Comment by shivin9** [comment]
https://github.com/JuliaDiffEq/DiffEqOperators.jl/commit/2b9e0d9dc14f845fcf90c0bb8dbff0270d63f02a

**Comment by shivin9** [comment]
oops! wrong issue

**Comment by ChrisRackauckas** [comment]
Looking into it, it looks like it's just Robin BCs which are broken. The values seem to drift away from the true BC over time.

**Comment by shivin9** [comment]
yeah, I had pinged @dextorious about it long time back and made a notebook also.
