### ISSUE TITLE
Broken KdV tests

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqOperators.jl#37]
Currently commented out because it stalls on CI

https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/test/runtests.jl#L11

**Comment by ChrisRackauckas** [comment]
KdV tests are now running, but they are still broken and do not converge correctly.

**Comment by ChrisRackauckas** [comment]
Since the single soluton works and it's just the dual soluton tests that are failing, but those are converging to something, I wonder if the analytical solution is written down wrong.

**Comment by shivin9** [comment]
well whatever it is, the solution is some form of a travelling wave only. But currently we see the waves 'splashing'. Don't know why that is happening when the 1D-Advection problem is getting solved correctly
