### ISSUE TITLE
unbalanced error for first order derivative - drift term

### ISSUE THREAD

**Issue by AshtonSBradley** [SciML/DiffEqOperators.jl#399]
If I add a drift term to any of the examples, I get an unbalanced error. Also happens if I remove diffusion and just have drift, as below for Dirichlet

```julia 
using OrdinaryDiffEq, ModelingToolkit, DiffEqOperators
# Method of Manufactured Solutions: exact solution
u_exact = (x,t) -> exp.(-t) * cos.(x)

# Parameters, variables, and derivatives
@parameters t x
@variables u(..)
Dt = Differential(t)
Dx = Differential(x)
Dxx = Differential(x)^2

# 1D PDE and boundary conditions
eq  = Dt(u(t,x)) ~  Dx(u(t,x)) #+ Dxx(u(t,x))
bcs = [u(0,x) ~ cos(x),
        u(t,0) ~ exp(-t),
        u(t,1) ~ exp(-t) * cos(1)]

# Space and time domains
domains = [t ∈ IntervalDomain(0.0,1.0),
           x ∈ IntervalDomain(0.0,1.0)]

# PDE system
pdesys = PDESystem(eq,bcs,domains,[t,x],[u(t,x)])

# Method of lines discretization
dx = 0.1
order = 2
discretization = MOLFiniteDifference([x=>dx],t)

# Convert the PDE problem into an ODE problem
prob = discretize(pdesys,discretization)

# Solve ODE problem
using OrdinaryDiffEq
sol = solve(prob,Tsit5(),saveat=0.2)

# Plot results and compare with exact solution
x = (0:dx:1)[2:end-1]
t = sol.t

using Plots
plt = plot()

for i in 1:length(t)
    plot!(x,sol.u[i],label="Numerical, t=$(t[i])")
    scatter!(x, u_exact(x, t[i]),label="Exact, t=$(t[i])")
end
display(plt)
savefig("plot.png")
```
throws 

ERROR: LoadError: InvalidSystemException: The system is unbalanced. There are 20 highest order derivative variables and 11 equations.
Stacktrace:
 [1] check_consistency(s::SystemStructure)
   @ ModelingToolkit.StructuralTransformations ~/.julia/packages/ModelingToolkit/Mo4gw/src/structural_transformation/utils.jl:59
 [2] structural_simplify(sys::ODESystem)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/Mo4gw/src/systems/abstractsystem.jl:638
 [3] discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{Vector{Pair{Num, Float64}}, Num})
   @ DiffEqOperators ~/.julia/packages/DiffEqOperators/DMNmH/src/MOLFiniteDifference/MOL_discretization.jl:226
 [4] top-level scope
   @ ~/.julia/dev/PHSI365ComputationalPhysics/projects/ThermalStorage/test_drift.jl:31
in expression starting at /Users/abradley/.julia/dev/PHSI365ComputationalPhysics/projects/ThermalStorage/test_drift.jl:31

**Comment by tinosulzer** [comment]
Can you try using the branch in #390 ?

**Comment by AshtonSBradley** [comment]
> Can you try using the branch in #390 ?

Runs without error and produces reasonable results. Works for pure drift, and also drift+diffusion. Admittedly I haven't been able to test very thoroughly yet

**Comment by ChrisRackauckas** [comment]
Great thanks for testing it out. Exciting to see it develop.
