### ISSUE TITLE
Readme example is probably outdated

### ISSUE THREAD

**Issue by DolineanuMircea** [SciML/DiffEqOperators.jl#401]
I have tried running the readme example 1 and I encountered an error when it came to the discretization. In the readme `discretization = MOLFiniteDifference(dx,order)` and causes `prob = discretize(pdesys,discretization)` to give a "type Int64 has no field val" error. In the docs, the line is changed to `discretization = MOLFiniteDifference([x=>dx],t)` and everything works fine. My guess is that the readme hasn't been updated after some changes were made.

**Comment by ChrisRackauckas** [comment]
yes, the README just hasn't been updated yet.
