### ISSUE TITLE
CenteredDifference gives zero matrix with constant coeff_func

### ISSUE THREAD

**Issue by hurricane007** [SciML/DiffEqOperators.jl#411]
when we have 
`x = collect(0:0.01:1)`
these two give different result: 
`CenteredDifference(2,2,0.01, length(x))*RobinBC((1.0, -1.0, 1.0), (0., 1.,0.), 0.01, length(x))*exp.(x)`
` CenteredDifference(2,2,0.01, length(x), 1)*RobinBC((1.0, -1.0, 1.0), (0., 1.,0.), 0.01, length(x))*exp.(x)`
the only difference is only coefficient function. 
actually, no matter what the coeff_fun is, CenteredDifference gives a zero matrix
`Array(CenteredDifference(2,2,0.01, length(x), constant))`

**Comment by hurricane007** [comment]
is it version related issue? 
![image](https://user-images.githubusercontent.com/16286632/122921423-c167e780-d362-11eb-9ac3-67827c1fef00.png)

**Comment by ChrisRackauckas** [comment]
I don't think that would be a versioning issue.

**Comment by hurricane007** [comment]
More interestingly, 
`Array(UpwindDifference(2,2,0.01, length(x), -1))` 
is not zero matrix, while 
`Array(UpwindDifference(2,2,0.01, length(x))) `
is zero matrix.

**Comment by ChrisRackauckas** [comment]
Upwinding operators need coefficients in order to be well-defined. We should probably even just error if it doesn't have coefficients (or maybe people assume the coefficient it 1?)

**Comment by hurricane007** [comment]
> Upwinding operators need coefficients in order to be well-defined. We should probably even just error if it doesn't have coefficients (or maybe people assume the coefficient is 1?)

I am using this package to solve the convection-diffusion equation with this form: 
du/dt = - usg*du/dz + De*d^u/dz^2 + s, 
when usg > 0, the coefficient is <0. I don't know others, but for me I would assume the coefficient is -1....
