### ISSUE TITLE
Add tests for central differences for a 2nd order operator

### ISSUE THREAD

**Issue by jlperla** [SciML/DiffEqOperators.jl#46]
I think we should probably add in a new test in https://github.com/JuliaDiffEq/DiffEqOperators.jl/tree/master/test called `univariate_diffusion.jl` or something like that.  The steps will be to create simple tests (where https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/test/derivative_operators_interface.jl already has much of the starting code)

For the following notation
- Let $W_t$ be standard Brownian motion with a unit variance
- Let $X_t$ be defined on $[\underline{x}, \bar{x}]$ where we will try different boundary values at these corners
- For an absorbing boundary, see https://github.com/econtoolkit/continuous_time_methods/blob/master/operator_discretization_finite_differences.pdf for some notes, but assume that the boundary for some function $v(x)$ has $v(\underline{x}) = \underline{v}$ and  $v(\bar{x}) = \bar{v}$ and 

I would test the generation with the following
- [ ] Simple $d X_t = d W_t$ discretization with central differences and reflecting boundaries at $\underline{x}$ and $\bar{x}$
- [ ] Simple $d X_t = d W_t$ discretization with central differences and with an absorbing boundary at $\underline{x}$ and a reflecting boundary at $\bar{x}$.  For the absorbing barrier, test $\underline{v}= 0$
- [ ] Simple $d X_t = d W_t$ discretization with central differences and with a reflecting boundary at $\underline{x}$ and an absorbing boundary at $\bar{x}$.  For the absorbing barrier, test $\bar{v} = 0$
- [ ] $d X_t = \sigma d W_t$ discretization with central differences and reflecting boundaries at $\underline{x}$ and $\bar{x}$.  Let $\sigma > 0$
- [ ] $d X_t = \sigma(X_t) d W_t$ discretization with central differences and reflecting boundaries at $\underline{x}$ and $\bar{x}$.  Ensure $\sigma(\cdot) > 0$ but make sure you test variation in the $\sigma(\cdot)$ function.
- [ ] Simple $d X_t = \sigma(X_t) d W_t$ discretization with central differences and with an absorbing boundary at $\underline{x}$ and a reflecting boundary at $\bar{x}$.  For the absorbing barrier, make sure to try  $\underline{v} = 0$ and make sure there is variation in the $\sigma(\cdot)$ function.

**Comment by ChrisRackauckas** [comment]
Agreed, but we please write those equations in the weak PDE form so it's easier to do the translation. To keep things simple, it's just the heat equation $$ u_t = \sigma(u)u_xx $$. There are some heat equation tests already: 

https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/test/heat_eqn.jl

but it never hurts to add more.

**Comment by jlperla** [comment]
Shouldn't that be $\sigma(x)$ for the variation (i.e. still linear PDE)?

**Comment by ChrisRackauckas** [comment]
Yes thanks. Fixed.

**Comment by jlperla** [comment]
Maybe we can put in comments in the tests that mention both the PDE and stochastic process forms.  Economists/finance people will find it much easier to think in terms of stochastic processes than the resulting PDEs.  Also, don't forget that those are frequently NOT the PDEs that would come out of the discretized operators (e.g. backwards equations are different and the variational-inequalities that come out of stopping problems are also very different from that).

**Comment by jlperla** [comment]
Note, given the grid `x_grid` to find the discretized $\sigma(x) d W_t$ operator, you should do something like `sigma(x_grid)' *  DerivativeOperator(...) * sigma(x_grid)` where the parameters for the derivative operator are the same as the one without the changing variance.

**Comment by ChrisRackauckas** [comment]
Correction, you need the `u` in there to apply the operator.

```julia
sigma(x_grid)' * DerivativeOperator(...) * u * sigma(x_grid)
```

**Comment by jlperla** [comment]
Note: only test the absorbing barrier with a value of 0 for now.

**Comment by jlperla** [comment]
Again, come back to this after #51 is complete.
