### ISSUE TITLE
Noob Help: Simple, Linear, Inhomogenous PDE

### ISSUE THREAD

**Issue by JGSuw** [SciML/DiffEqOperators.jl#479]
My apologies in advance if this is the wrong venue for my query. I am a complete novice in the realm of PDEs, and I am struggling to grasp how to use DiffEqOperators to solve linear PDEs.

My general problem structures is as follows: I have a known function `f` from R^n into R^n and an unknown function `u` from R^n into R. I want to find a solution to the equation `Du = f`. At this point I don't care about boundary conditions, I would be grateful if someone could show me how to do this for some particular boundary condition.

For the sake of argument, suppose that `f(x,y) = (2x,3y^2)`  is the function on the right hand side. I would like to approximate a solution to the PDE on the domain `(-1,1)^2`. Solving this PDE obviously will involve the _total derivative_ ( _push-forward_) of `u`.

In general, I would like to be able to solve these problems where `n>2`, and possibly when `u` is a function from R^n to R^p.

Thanks in advance for any assistance that you can provide.

P.S. If it interests you at all, present application for this problem is for generating adapted charts of a fibered manifold on some open neighborhood and given a chart for the total space and a chart for the base space.

**Comment by tinosulzer** [comment]
At first glance it looks like what you want to solve is 
```
Dx(u) ~ 2x
Dy(u) ~ 3y^2
```
which has the solution `u = x^2 + y^3`. Is that correct? If so, you can do it by specifying a bunch of first-order 1D ODEs with solutions `u1` ... `un` and then `u = u1 + ... + un`.

**Comment by JGSuw** [comment]
Yes, quite literally I want a multivariate function `u` that is an antiderivative of `f` on it's domain. In the toy example I gave there is a simple analytic solution `u(x,y) = x^2+y^3+C` for real `C`. In reality my application will involve complicated `f` and most likely will _not_ have analytic solutions. However, since this system of equations is obviously a linear PDE, my hope was that using suitable discretization tools (e.g. _DiffEqOperators_), I could approximate the solution to this problem on a grid by solving some linear system of equations `AU-B`.

I think what you are suggesting is, roughly speaking, to specify the function value on part of the boundary (initial conditions to the ODEs) and integrate them. However, it's not clear to me how to do this in a way that yields a function which is consistent with the system of equations, hence why my attention has turned to tools used to solve PDEs.

**Comment by JGSuw** [comment]
I will close this because it has dawned upon me that I do not yet know for sure whether my vector field _f_ is even conservative. If it is not, then this problem is not well posed.
