### ISSUE TITLE
Implementing Drift-Diffusion model in higher dimensions

### ISSUE THREAD

**Issue by apekshasingh** [SciML/DiffEqOperators.jl#518]
Hi there!  Thanks so much for your package.  I'm trying to implement a drift-diffusion model with additional source/sink terms in 2-4 space dimensions.  More specifically: 
![image](https://user-images.githubusercontent.com/50004909/168698147-30991327-58b6-46ce-a42e-ff1e555dc456.png)

I'm really only interested in solving for the steady state solution of c (at least for now).  I'm trying to get a sense of how this package works and I'm just trying to implement something simple to start.  Sticking with just 2 dimensions for now and just trying to implement the first term of the model I have:

using DiffEqOperators, LinearAlgebra
n = 100
delta = 1/n

Dxx = CenteredDifference{1}(2, 2, delta, n)
Dyy = CenteredDifference{2}(2, 2, delta, n)
L = Dxx + Dyy

BCx = MultiDimBC{1}(DirichletBC(1.0, 0.0), (n,n))
BCy = MultiDimBC{2}(DirichletBC(1.0, 0.0), (n,n)) _(actual model will have Neumann type BC)_
BC = compose(BCx, BCy)

Laplace = L * BC

c = Laplace\zeros(n) _(I don't believe this is correct.  I want to just solve for steady state, but I'm quite not sure how to implement solving the system of linear equations)_

I think I'm not quite understanding how to use these DerivativeOperator objects.  Any help getting on the right track would be greatly appreciated!  Thank you so much!

**Comment by xtalax** [comment]
Another thing, we need a steady state tutorial, if you get this working in MethodOfLines please post an issue with your code and I will include it in the docs.
