### ISSUE TITLE
Next steps for the documentation and tests for simple cases

### ISSUE THREAD

**Issue by FernandoKuwer** [SciML/DiffEqOperators.jl#57]
This issue summarizes the main takeaways from the meeting that Steven and I had last Thursday:
i) We agreed that the first thing is to check if the ghost nodes approach suggested in Chris/Jesse tread (https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/260) indeed maps the problem we are trying to solve.
ii) In order to do that, we think we should test this approach vs some simple problem, ideally, one with analytical solution

Based on that, we defined that our planned next steps are:
- [ ] Finishing writing the linear_operators_overview.tex 
- [ ] Look for simple processes with known solution for future tests of the new approach (especially a jump-diffusion) 
- [ ] test the approach for a simple diffusion process (one dimensional, no drift)

**Comment by jlperla** [comment]
Just to verify, by the "known solution" here, we are thinking known discretization matrices.  I think implementing the matrices and HJBE for the ones listed at the end of `https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/univariate_tests/docs/linear_operators_overview.tex` is enough to get started.

**Comment by FernandoKuwer** [comment]
@stevenzhangdx
